### ISSUE TITLE
Repository in package.json pointing to wrong repository

### ISSUE THREAD

**Issue by eirikb** [tonyheupel/node-pingdom-client#1]
Hey

It seems your package.json is pointing to "git://github.com/jashkenas/coffee-script.git" ( https://github.com/tchype/node-pingdom-client/blob/master/package.json#L19 ).
Could you please update this to "https://github.com/tchype/node-pingdom-client"?
The current information could be misleading, as seen here: http://eirikb.github.com/nipster/#coffee (where your package is now at top)

**Comment by tonyheupel** [comment]
You bet.  I don't know why I did that at all.  I can see how that's misleading.

Changed.  Thanks for pointing that out!

**Comment by timoxley** [comment]
Hey can you please publish this change on npm? `npm info pingdom-client` still reports the wrong repo.

**Comment by tonyheupel** [comment]
Published to npm.  Sorry about that.

**Comment by timoxley** [comment]
Thanks, no worries. I was just wondering why this repo was coming up incredibly high in [module rankings](http://nodejsmodules.org/)…
Not saying there's anything wrong with your module, it just seemed absurdly popular. Jinja also suffers the same symptoms.
![http://nodejsmodules.org/](http://i.imgur.com/mclqR.png)
